prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix sh: <http://www.w3.org/ns/shacl#>

construct {
  ?n <> ?cm_s; ?class_member ?rn_class .
  ?n <> ?dtcm_s .
}
where {
  ?n rdf:type rdfs:Class .
  optional { ?n sh:property [ sh:path ?class_member; sh:class ?rn_class] bind(concat(str(?class_member), " ", str(?rn_class)) as ?cm_s) }
  optional { ?n sh:property [ sh:path ?dtc_member; sh:dataclass ?rn_dataclass] bind(concat(str(?dtc_member), " xsd:", strafter(str(?rn_dataclass), str(xsd:))) as ?dtcm_s) }
}
